swagger: "2.0"

info:
  title: Applicant Summary API
  version: "1.0"

host: get-this-bread.vercel.app
basePath: /api

schemes:
  - https

paths:
  /applicant-summary:
    get:
      operationId: RetrieveApplicantRecord
      summary: Retrieve applicant record

      parameters:
        - name: id
          in: query
          required: true
          type: string

      responses:
        "200":
          description: Applicant data

          schema:
            type: object

            properties:
              id:
                type: string
              name:
                type: string
              jobTitle:
                type: string
              status:
                type: string
              source:
                type: string
              appliedDate:
                type: string
              recruiter:
                type: string
              email:
                type: string
              phone:
                type: string
              location:
                type: string
              skills:
                type: string
              education:
                type: string
              professionalSummary:
                type: string
              experienceSummary:
                type: string
              coverLetter:
                type: string
